services:
  frontend:
    image: hrmstrailblazer/234-deploylab-frontend:latest
    pull_policy: always
    ports:
      - "8081:8080"
    restart: unless-stopped
    environment:
      - VITE_GRAPHQL_URI=http://54.197.53.201:8082/graphql
      - VITE_SERVER_URI=http://54.197.53.201:8082